# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('perc', ['internet', 'point-to-point', 'applications', 'traffic-control', 'flow-monitor'])
    
    module.source = [
        'model/perc.cc',
        'helper/perc-helper.cc',
        'model/convergence-experiments.cc',
        ]

    # module_test = bld.create_ns3_module_test_library('perc')
    # module_test.source = [
    #     'test/perc-test-suite.cc',
    #     ]

    headers = bld(features='ns3header')
    headers.module = 'perc'
    headers.source = [
        'model/perc.h',
        'helper/perc-helper.h',
        'model/convergence-experiments.h',
    ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

